version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
  nexus:
    image: sonatype/nexus3
    restart: always
    volumes:
      - /home/nexus/nexus-data:/nexus-data
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
  sonar:
    image: sonarqube
    restart: always
    volumes:
      - /home/sonarqube/data:/opt/sonarqube/data
    ports:
      - 9000:9000
  mysqldb:
    restart: always
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_volume:/var/lib/mysql
  spring_app:
    image: tp_achat
    container_name: tp_achat
    restart: on-failure
    ports:
      - 8090:8089
    depends_on:
      - mysqldb     
volumes:
 jenkins_home:
   external: true
 mysql_volume:
   external: true 
